name: build_and_push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest-m

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Free up disk space (20~40GB)
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/share/boost || true
          sudo rm -rf /usr/local/graalvm || true
          sudo rm -rf /usr/local/share/chromium || true
          sudo rm -rf /usr/local/share/chrome_driver || true
          sudo apt-get remove -y '^dotnet-.*' || true
          sudo apt-get remove -y '^llvm-.*' || true
          sudo apt-get remove -y 'php.*' || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          docker system prune -af --volumes
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: false
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/worker-comfyui-v3:${{ github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/worker-comfyui-v3:latest
          build-args: |
            MODEL_TYPE=none

      - name: Cleanup Docker (free space)
        if: always()
        run: |
          docker buildx prune -af || true
          docker system prune -af || true
          df -h
